USE aula3exer1;

DROP TABLE possui;
DROP TABLE pertence;
DROP TABLE trabalha;
DROP TABLE ESPECIALIDADE;
DROP TABLE TURNO;
DROP TABLE PLANTONISTA;
DROP TABLE SETOR;

DROP ROLE administrador;
DROP ROLE usuario;
DROP ROLE gestor;

